config/routes.rb
Rails.application.routes.draw do
    resources :databases, only: [:show]

    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
    }

    resources :projects, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
        resources :collaborators, only: [:new, :create, :update, :destroy]
        resources :databases, only: [:index, :create]
    end

    resources :databases, only: [] do
        resources :tables, only: [:index, :create] do
            resources :comments, only: :create
        end
    end

    resources :mysql_databases, only: [] do
        resources :tables, only: [:index, :create] do
            resources :comments, only: :create
        end
    end

    resources :database_table_preferences, only: :update

    resources :columns, only: [:create, :destroy] do
        resources :comments, only: :create
    end

    resources :comments, only: :destroy

    root to: 'pages#home'
    get '/privacy-policy', to: 'pages#privacy'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_collab_modal.html.erb
<div class="modal fade" id="collabModal" tabindex="-1" role="dialog" aria-labelledby="collabModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title modal-header" id="collabModalTitle">Add Collaborator</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fas fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <%= render 'collaborators/form', project: @project, collaborator: @collaborator %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_collaborator_edit_modal.html.erb
<div class="modal fade" id="collaborator-edit-modal" tabindex="-1" role="dialog" aria-labelledby="collaborator-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title modal-header" id="collaborator-modal-title">Update Collaborator</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fas fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <%= render 'collaborators/edit_form', project: @project, collaborator: @collaborator %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_collaborator_modal.html.erb
<div class="modal fade" id="collaborator-modal" tabindex="-1" role="dialog" aria-labelledby="collaborator-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title modal-header" id="collaborator-modal-title">Add Collaborator</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fas fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <%= render 'collaborators/form', project: @project, collaborator: @collaborator %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_database_modal.html.erb
<div class="modal fade" id="database-modal" tabindex="-1" role="dialog" aria-labelledby="database-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title modal-header" id="database-modal-title">Add Database</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fas fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <%= render 'databases/form'%>
            </div>
        </div>
    </div>
</div>

app/views/shared/_db_modal.html.erb
<div class="modal fade" id="dbModal" tabindex="-1" role="dialog" aria-labelledby="dbModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title modal-header" id="dbModalTitle">Add Database</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fas fa-times"></i></span>
                </button>
            </div>
            <div class="modal-body">
                <%= render 'databases/form'%>
            </div>
        </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
    <div id="alert" class="alert alert-info alert-dismissible fade show m-1" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<% if alert %>
    <div id="alert"  class="alert alert-warning alert-dismissible fade show m-1" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="our-footer">
    <div class="container-footer">
        <div class="footer-links">

        <!-- Link to GitHub repo -->
        <a href="https://github.com/SeeQL-Enterprises/SeeQL" target="_blank">
            <i class="fab fa-github-square"></i>
        </a>

        <!-- Link to Twitter profile -->
        <a href="https://twitter.com/see_ql" target="_blank">
            <i class="fab fa-twitter-square"></i>
        </a>

        <!-- Link to LinkedIn page -->
        <a id="clipboard-button" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" data-placement="top" data-content="">
            <i class="fab fa-linkedin"></i>
        </a>

        <!-- Link to support e-mail -->
        <a href="mailto: support@seeql.dev" target="_blank">
            <i class="fas fa-envelope-square"></i>
        </a>

        <!-- Link to share on Facebook -->
        <!-- <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.seeql.dev%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">
            <i class="fab fa-facebook-square"></i>
        </a> -->
        </div>
        <div class="footer-copyright">
            Coded with 🦄 @ SeeQL
        </div>
    </div>
</div>

app/views/shared/_login_modal.html.erb
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="login-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title modal-header" id="login-modal-title">Login</h5>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fas fa-times"></i></span>
                </button> -->
            </div>
            <div class="modal-body">
                <div class="login-errors"></div>
                <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), remote: true, html: { id: :login_form }) do |f| %>
                    <div class="form-inputs">
                        <%= f.input :email, required: false, autofocus: true, input_html: { autocomplete: "email", id: "login-email" }, placeholder: "jane.doe@gmail.com" %>
                        <%= f.input :password, required: false, input_html: { autocomplete: "current-password", id: "login-password" }, placeholder: "DatabasesAreAwesome" %>
                        <%= f.input :remember_me, as: :boolean, input_html: {id: "user-remember-me"} if devise_mapping.rememberable? %>
                        <ul id="help-list">
                            <li>
                                <button id="help-button" type="button">
                                    <i class="far fa-question-circle"></i>
                                </button>
                                <ul id="help-nested-list">
                                        <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
                                            <li>
                                                <%= link_to "Forgot your password?", new_password_path(resource_name), class: "" %><br />
                                            </li>
                                        <% end %>
                                        <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
                                            <li>
                                                <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
                                            </li>
                                        <% end %>
                                        <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
                                            <li>
                                                <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
                                            </li>
                                        <% end %>
                                </ul>
                            </li>
                        </ul>
                    </div>
                <% end %>
            </div>
            <div class="modal-footer">
                <%- if devise_mapping.omniauthable? %>
                    <%- resource_class.omniauth_providers.each do |provider| %>
                        <% provider_logo = "" %>

                        <% case provider
                        when :github %><% provider_logo = "fab fa-github" %>
                        <% else %>
                            <% "Invalid provider" %>
                        <% end %>
                        <%= link_to user_github_omniauth_authorize_path, method: :post do %>
                            <button type="button" class="btn-seeql btn-seeql-lg <%= "#{OmniAuth::Utils.camelize(provider).downcase}" %>-button">
                                <%= "Sign in with #{OmniAuth::Utils.camelize(provider)}" %>&nbsp;&nbsp;<i class="<%= provider_logo %>"></i>
                            </button>
                        <% end %>
                    <% end %>
                <% end %>
                <button id="login-button-form" type="submit" form="login_form" class="btn-seeql btn-seeql-lg">
                    Log in
                </button>
            </div>
        </div>
    </div>
</div>

app/views/shared/_menu.html.erb
<!-- SIDEBAR-MENU -->
<div class="sidebar-menu">
    <input type="checkbox" id="sidebar-toggle">
    <label for="sidebar-toggle" >
        <svg  viewbox="0 0 100 100" width="100%" height="100%">
            <circle cx="50" cy="50"></circle>
        </svg>
        <% if current_user %>
            <% if current_user.avatar.attached? %>
                <div class="avatar" id="sidebar-opener">
                    <%= cl_image_tag current_user.avatar.key %>
                </div>
            <% else %>
                <div class="avatar" id="sidebar-opener">
                    <%= image_tag("avatar.svg", id: "sidebar-opener") %>
                </div>
            <% end %>
        <% else %>
            <div class="hamburger" id="sidebar-opener">
                <div class="center"></div>
            </div>
        <% end %>
    </label>
</div>

<!-- Sidebar Nav -->
<div id="sidebar" class="sidebar">
    <div class="sidebar-text">
        <%= link_to "Home", root_path, class: "border-bottom" %>
        <% if current_user %>
            <%= link_to "My Projects", projects_path, class: "border-bottom" %>
            <%= link_to "Create Project", new_project_path, class: "border-bottom" %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "border-bottom" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "border-bottom" %>
        <% else %>
            <a id="login-button-sidebar" class="border-bottom" type="button" data-toggle="modal" data-target="#login-modal">
                    Login
            </a>
        <% end %>
        <% if !current_user %>
            <a id="signup-button-sidebar" class="border-bottom" type="button" data-toggle="modal" data-target="#signup-modal">
                Sign Up
            </a>
        <% end %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-seeql">
    <%= link_to root_path, class: "navbar-brand" do %>
        <h5>SeeQL</h5>
    <% end %>
    <% if request.original_url.include?("/projects/") %>
    <div class="navbar-back-buttons">
        <a href="/projects">
            <button class="btn-seeql btn-seeql-lg btn-seeql-transparent" style="display: flex; align-items: center;">
                <i class="fas fa-caret-left" style="font-size: 28px;"></i>&nbsp;Back to projects
            </button>
        </a>
    </div>
    <% end %>
</div>

<%= render 'shared/login_modal' %>
<%= render 'shared/signup_modal' %>

app/views/shared/_signup_modal.html.erb
<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="signup-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title modal-header" id="signup-modal-title">Sign Up</h5>
            </div>
            <div class="modal-body">
                <div class="signup-errors"><ul class="signup-errors-list"></ul></div>
                <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), remote: true, html: { id: :signup_form }) do |f| %>
                    <%= f.error_notification %>
                    <div class="form-inputs">
                        <%= f.input :first_name, required: true, autofocus: true %>
                        <%= f.input :last_name, required: true %>
                        <%= f.input :email, required: true, autofocus: true, input_html: { autocomplete: "email", id: "signup-email" } %>
                        <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), input_html: { autocomplete: "new-password", id: "new-password" } %>
                        <%= f.input :password_confirmation, required: true, input_html: { autocomplete: "new-password", id: "confirm-password" } %>
                    </div>
                <% end %>
            </div>
            <div class="modal-footer">
                <button id="signup-button-form" type="submit" form="signup_form" class="btn-seeql btn-seeql-lg">
                    Sign up
                </button>
            </div>
        </div>
    </div>
</div>