config/routes.rb
Rails.application.routes.draw do
    resources :databases, only: [:show]

    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
    }

    resources :projects, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
        resources :collaborators, only: [:new, :create, :update, :destroy]
        resources :databases, only: [:index, :create]
    end

    resources :databases, only: [] do
        resources :tables, only: [:index, :create] do
            resources :comments, only: :create
        end
    end

    resources :mysql_databases, only: [] do
        resources :tables, only: [:index, :create] do
            resources :comments, only: :create
        end
    end

    resources :database_table_preferences, only: :update

    resources :columns, only: [:create, :destroy] do
        resources :comments, only: :create
    end

    resources :comments, only: :destroy

    root to: 'pages#home'
    get '/privacy-policy', to: 'pages#privacy'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :table, optional: true
    has_many :comments, as: :commentable
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
    def create
        @column = Column.new(column_params)
        authorize @column
        @database = @column.table.database

        @column.save!

        respond_to do |format|
            format.js do
                @counter = params[:column_proxy][:counter]
                @table = @column.table
            end

            format.html { redirect_to database_tables_path(@database) }
        end
    end

    def destroy
        @column = Column.find(params[:id])
        @database = @column.table.database
        authorize @column

        @column.destroy if @column.edit

        respond_to do |format|
            format.js
            format.html { redirect_to database_tables_path(@database) }
        end
    end

    private

    def column_params
        params.require(:column_proxy).permit(:name, :datatype, :table_id, :edit)
    end
end

app/views/columns/_column.html.erb
<div class="column text-center <%= 'edit' if column.edit %>" data-column-id="<%= column.id %>">
    <div class="comments-list">
        <% unless column.comments.blank? %>
            <% column.comments.each do |comment| %>
                <div id="comments" class="column comment-content" data-comment-id="<%= comment.id %>">
                    <p class="subheader"><strong><%= comment.user.name %>: </strong><%= comment.content %></p>
                    <%= link_to comment_path(comment), method: :delete, remote: true do %>
                        <i class="fas fa-times" aria-hidden="true"></i>
                    <% end %>
                </div>
            <% end %>
        <% end %>
    </div>
    <div class="comment-button text-right" data-commentbutton="<%= counter %>"><i class="fas fa-ellipsis-h"></i>
        <div class="d-flex justify-content-between">
            <div class="column-comment column-name subheader"> <%= column.name %>
            </div>
            <div class="column-comment subheader"> <span class="hidden-text"><%= column.datatype %></span>
            </div>
        </div>
    </div>
</div>
<div class="column comment hidden subheader" data-comment="<%= counter %>" data-column-id="<%= column.id %>">
    <div class="text-center mt-3">
        <p><strong>Edit</strong> this column</p>
    </div>
    <div class="text-center">
        <%= link_to column_path(column), method: :delete, remote: true do %>
            <p><strong>Delete</strong> this column</p>
        <% end %>
    </div>
    <button type="button" class="plus-button w-100" data-toggle="modal" data-target="#create-comment-<%= table.id %>-<%= column.id %>">
        <p><strong>Add a comment</strong> </p>
    </button>
</div>

app/views/columns/_form.html.erb
<%= simple_form_for(:column_proxy, url: columns_path, method: :post, remote: true) do |f| %>
    <%= f.input :name %>
    <%= f.input :datatype, collection: Table::DATATYPES %>
    <%= f.input :table_id, :input_html => { :value => table.id }, as: :hidden %>
    <%= f.input :edit, :input_html => { :value => true }, as: :hidden %>
    <%= f.input :counter, :input_html => { :value => counter }, as: :hidden %>
    <label class="btn-seeql btn-seeql-lg" style="color: white !important">Add column
        <span style="display: none"><%= f.submit as: "Add Column" %></span>
    </label>
<% end %>

app/views/columns/create.js.erb
document.querySelector('#column_proxy_name').value = "";
document.querySelector('#column_proxy_datatype').value = "";

var columnBox = `<%= render "column", counter: @counter, column: @column, table: @table %>`;
var commentList = document.querySelector('[data-table-id="<%= @table.id %>"]');

commentList.insertAdjacentHTML('beforeend', columnBox);

app/views/columns/destroy.js.erb
var box = document.querySelector('[data-column-id="<%= @column.id %>"]')
var options = document.querySelector('.column.comment[data-column-id="<%= @column.id %>"]')

box.remove()
options.remove()