config/routes.rb
Rails.application.routes.draw do
    resources :databases, only: [:show]

    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
    }

    resources :projects, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
        resources :collaborators, only: [:new, :create, :update, :destroy]
        resources :databases, only: [:index, :create]
    end

    resources :databases, only: [] do
        resources :tables, only: [:index, :create] do
            resources :comments, only: :create
        end
    end

    resources :mysql_databases, only: [] do
        resources :tables, only: [:index, :create] do
            resources :comments, only: :create
        end
    end

    resources :database_table_preferences, only: :update

    resources :columns, only: [:create, :destroy] do
        resources :comments, only: :create
    end

    resources :comments, only: :destroy

    root to: 'pages#home'
    get '/privacy-policy', to: 'pages#privacy'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user

    has_many :databases
    has_many :collaborators, dependent: :destroy

    has_one_attached :project_image

    validates :name, presence: true, on: :create
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
        @projects = policy_scope(Project)
    end

    def show
        @collaborator = Collaborator.new
        @project = Project.find(params[:id])
        @database = @project.databases
        authorize @project
    end

    def new
        @project = Project.new
        authorize @project
    end

    def create
        @project = Project.new(project_params)
        authorize @project
        @project.user = current_user

        if @project.save!
            redirect_to project_path(@project)
        else
            render :new
        end
    end

    def edit
        @project = Project.find(params[:id])
        authorize @project
    end

    def update
        @project = Project.find(params[:id])
        authorize @project
        @project.update(project_params)

        if @project.save!
            redirect_to project_path(@project), notice: 'Project successfully updated!'
        else
            render :edit
        end
    end

    def destroy
        @project = Project.find(params[:id])
        authorize @project
        @project.destroy
        redirect_to projects_path, notice: 'Project has been deleted!'
    end

    private

    def project_params
        params.require(:project).permit(:name, :project_image)
    end

    def project_members
        @project.collaborators.map { |collaborator| collaborator.user.id }.push(current_user.id)
    end
end

app/views/projects/edit.html.erb
<div class="container">
    <div class="container-wide content-wide">
        <div class="form-content">
            <div class="form-header">
                <div class="container-double">
                    <h2 class="form-title">Edit project below</h2>
                </div>
            </div>
            <div class="form-body">
                <div class="container-double">
                    <%= simple_form_for @project, html: { id: "project-form", class: "flex-form" } do |f| %>
                        <div class="form-inputs w-1/2 max-w-lg">
                            <div class="flex flex-wrap -mx-5">
                                <div class="w-full px-4">
                                    <%= f.input :name, required: true, class: "form-control appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white", input_html: { id: "name-new-project", placeholder: "Name of your new project" } %>
                                </div>
                            </div>
                        </div>
                        <div class="form-content form-image">
                            <div class="project-image-preview">
                                <img id="project-preview-image" class="card-image" src="https://res.cloudinary.com/seeql/image/upload/v1592580690/General%20Assets/Project%20Placeholder.png" alt="User's current profile image" style="object-fit: contain;">
                                <label id="project-image-button" type="button" class="btn-seeql btn-seeql-lg upload-button">
                                    <span id="project-image-button-text">
                                        Choose project image
                                    </span>
                                    <span style="display: none;">
                                        <%= f.input :project_image, as: :file, required: false, input_html: { id: "project-image" } %>
                                    </span>
                                </label>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="form-footer">
                <div class="container-double">
                    <%= link_to :back do %>
                        <button id="back-button-edit" type="button" class="btn-seeql btn-seeql-lg btn-seeql-red">
                            Back
                        </button>
                    <% end %>
                    <button type="submit" form="project-form" class="btn-seeql btn-seeql-lg">
                        Update
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/projects/index.html.erb
<div class="container-primary container-projects">
	<div class="container-wide flex-column">
		<div style="text-align: center;">
			<h1 class="heading-section" style="margin-top: 100px;">
				Your Projects
			</h1>
		</div>
		<div class="content-wide">
			<div class="d-flex" style="justify-content: center; padding: 35px;">
				<%= link_to new_project_path do %>
					<button class="btn-seeql btn-seeql-lg" style="margin-top: 20px;">
						<i class="fas fa-plus-circle"></i> Add Project
					</button>
				<% end %>
			</div>

			<% @projects.sort_by! { |project| project.created_at } %>

			<!-- Project card grid -->
			<div class="card-grid">
				<% @projects.each do |project| %>
					<div class="card-project">

						<div class="card-project-options">
							<i class="fas fa-ellipsis-h project-options-icon" type="button"></i>
							<div>
								<ul id="card-project-options-dropdown" style="margin-top: -10px; display: none;">
									<li class="seeql-red">
										<i class="fas fa-trash seeql-red" type="button" style="font-size: 18px;"></i>
										<span class="seeql-red" style="font-size: 20px"><%= link_to "Delete", project_path(project), method: :delete, data: {confirm: "Are you sure you want to delete the project?"} %></span>
									</li>
									<li class="seeql-red">
										<i class="fas fa-edit light-blue" type="button" style="font-size: 18px;"></i>
										<span class="light-blue" style="font-size: 20px"><%= link_to "Edit", edit_project_path(project) %></span>
									</li>
								</ul>
							</div>
						</div>

						<%= link_to project_path(project), style: "text-decoration: none;" do %>

							<!-- Project image -->
							<% if project.project_image.attached? %>
								<div class="card-image" style="background-image: linear-gradient(rgba(0, 0, 0, .7), rgba(0, 0, 0, .7)), url('<%= cl_image_path project.project_image.key %>')">
									<div class="card-project-title">
										<h2><%= project.name %></h2>
									</div>
								</div>
							<% else %>
								<div class="card-image" style="background-image: linear-gradient(rgba(0, 0, 0, .7), rgba(0, 0, 0, .7)), url('https://res.cloudinary.com/seeql/image/upload/v1585663675/Background_a0ecgr.png')">
									<div class="card-project-title">
										<h2><%= project.name %></h2>
									</div>
								</div>
							<% end %>

							<!-- Project collaborators -->
							<div class="card-project-infos">
								<div class="project-collaborators">
									<% project.collaborators.each do |collaborator| %>
										<div class="collaborator">
											<% if collaborator.user.avatar.attached? %>
												<div class="collaborator-avatar">
													<%= cl_image_tag collaborator.user.avatar.key %>
												</div>
											<% else %>
												<div class="collaborator-avatar">
													<%= image_tag("avatar.svg") %>
												</div>
											<% end %>
											<div class="collaborator-name">
												<%= collaborator.user.first_name %>
												<%= collaborator.user.last_name[0] %>.
											</div>
										</div>
									<% end %>
								</div>
							</div>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/projects/new.html.erb
<div class="container">
    <div class="container-wide content-wide">
        <div class="form-content">
            <div class="form-header">
                <div class="container-double">
                    <h2 class="form-title">Create a new project</h2>
                </div>
            </div>
            <div class="form-body">
                <div class="container-double">
                    <%= simple_form_for @project, html: { id: "project-form", class: "flex-form" } do |f| %>
                        <div class="form-inputs w-1/2 max-w-lg">
                            <div class="flex flex-wrap -mx-5">
                                <div class="w-full px-4">
                                    <%= f.input :name, required: true, class: "form-control appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white", input_html: { id: "name-new-project", placeholder: "Name of your new project" } %>
                                </div>
                            </div>
                        </div>
                        <div class="form-content form-image">
                            <div class="project-image-preview">
                                <img id="project-preview-image" class="card-image" src="https://res.cloudinary.com/seeql/image/upload/v1592580690/General%20Assets/Project%20Placeholder.png" alt="User's current profile image" style="object-fit: contain; width: 700px;">
                                <label id="project-image-button" type="button" class="btn-seeql btn-seeql-lg upload-button">
                                    <span id="project-image-button-text">
                                        Choose project image
                                    </span>
                                    <span style="display: none;">
                                        <%= f.input :project_image, as: :file, required: false, input_html: { id: "project-image" } %>
                                    </span>
                                </label>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="form-footer">
                <div class="container-double">
                    <%= link_to :back do %>
                        <button id="back-button-edit" type="button" class="btn-seeql btn-seeql-lg btn-seeql-red">
                            Back
                        </button>
                    <% end %>
                    <button type="submit" form="project-form" class="btn-seeql btn-seeql-lg">
                        Create
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/projects/show.html.erb
<%= render 'shared/collaborator_modal' %>
<%= render 'shared/collaborator_edit_modal' %>
<%= render 'shared/database_modal' %>

<div class="container" style="padding: 0 90px;">
    <div class="container-wide flex-column">
        <div style="text-align: center;">
            <h2 class="heading-form" style="margin-top: 100px;">
                Connect your
                <strong><span style="color: #5BC0BE;">
                    <%= @project.name %>
                </span></strong>
                project to a database and invite collaborators
            </h2>
        </div>

        <div class="content-wide" style="margin-top: 50px;">
            <div class="horizontal-btns">
                <button class="btn-seeql btn-seeql-darkgrey" data-toggle="modal" data-target="#collaborator-modal">
                    <i class="fas fa-user-plus"></i> Add Collaborator
                </button>
                <button class="btn-seeql btn-seeql-darkgrey" data-toggle="modal" data-target="#database-modal">
                    <i class="fas fa-database"></i> Add Database
                </button>
            </div>

                <div class="container-double" style="padding-top: 0; padding-bottom: 10px;">
                    <div class="collaborators-container">
                        <% @project.collaborators.each do |collaborator| %>
                            <div class="collaborator-card">
                                <% if collaborator.user.avatar.attached? %>
                                    <div class="avatar-large">
                                        <%= cl_image_tag collaborator.user.avatar.key %>
                                    </div>
                                <% else %>
                                    <div class="avatar-large">
                                        <%= image_tag("avatar.svg") %>
                                    </div>
                                <% end %>


                                <div class="collaborator-card-content">
                                    <p><small>Added: <%= collaborator.created_at.strftime("%B %d, %Y")%></small></p>
                                    <p><%= collaborator.user.email %></p>
                                </div>

                                <div class="collaborator-card-actions">
                                    <a href="#"><i class="fas fa-pencil-alt"></i>Edit</a>
                                    <%= link_to project_collaborator_path(@project, collaborator), method: :delete do %>
                                        <i class="far fa-trash-alt"></i>Delete
                                    <% end %>
                                </div>

                            </div>
                        <% end %>
                    </div>
                    <div class="database-button-container">
                        <% @project.databases.each do |database| %>
                            <%= link_to database_path(database) do %>
                                <button class="btn-seeql">
                                    Go to <%= database.name %>
                                </button>
                            <% end %>
                        <% end %>
                    </div>
                </div>

        </div>
    </div>
</div>