config/routes.rb
Rails.application.routes.draw do
    resources :databases, only: [:show]

    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
    }

    resources :projects, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
        resources :collaborators, only: [:new, :create, :update, :destroy]
        resources :databases, only: [:index, :create]
    end

    resources :databases, only: [] do
        resources :tables, only: [:index, :create] do
            resources :comments, only: :create
        end
    end

    resources :mysql_databases, only: [] do
        resources :tables, only: [:index, :create] do
            resources :comments, only: :create
        end
    end

    resources :database_table_preferences, only: :update

    resources :columns, only: [:create, :destroy] do
        resources :comments, only: :create
    end

    resources :comments, only: :destroy

    root to: 'pages#home'
    get '/privacy-policy', to: 'pages#privacy'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/databases_controller.rb
class DatabasesController < ApplicationController
    def show
        @comment = Comment.new
        @database = Database.find(params[:id])
        @project = @database.project
        @tables = @database.tables
        authorize @project
    end

    def create
        @db_accessor =
            if params[:new_database][:db_type] == 'PostgreSQL'
                PostgresAccessor.new(database_params)
            else
                MysqlAccessor.new(database_params)
            end

        authorize @db_accessor
        @db_accessor.call

        @project = Project.find(params[:project_id])

        redirect_to project_path(@project)
    end

    private

    def database_params
        params.require(:new_database).permit(:db_type, :name, :host, :port, :db_name, :user, :password, :project_id)
    end
end

app/views/databases/_form.html.erb
<% url = "/projects/#{@project.id}/databases" %>

<%= simple_form_for(:new_database, url: url, method: :post) do |f| %>

  <div class="form-inputs">
    <%= f.input :db_type, as: :select, collection: ['PostgreSQL', 'MySQL'], label: "DB Type", default: 'PostgreSQL' %>
    <%= f.input :name, label: "DB Nickname", placeholder: "DB nickname" %>
    <%= f.input :host, placeholder: "where is your DB hosted?" %>
    <%= f.input :port, placeholder: "optional port", required: false %>
    <%= f.input :db_name, label: "DB Name", placeholder: "the actual name of your DB" %>
    <%= f.input :user, placeholder: "user that will be connecting" %>
    <%= f.input :password, as: :password, placeholder: "we promise we won't save it!" %>
    <%= f.input :project_id, :input_html => { :value => @project.id }, as: :hidden %>
  </div>

  <div class="form-actions">
    <div class="modal-footer">
      <%= f.button :submit, "Connect Database!", class: "btn-seeql btn-seeql-lg" %>
    </div>
  </div>
<% end %>

app/views/databases/show.html.erb
<div class="container-primary">
    <h1>Which tables do you want to display?</h1>
    <div class="d-flex align-items-center">
        <button type="button" id='select-all' class="form-check"></button>
        <span class="label-select-all" id="select-all-text">Select all</span>
    </div>
    <%= simple_form_for(@database, url: database_table_preference_path(@database)) do |f| %>
        <%= f.input :tables, collection: @database.tables, as: :check_boxes, label_value: :name, input_html: { checked: false, class: "on" }%>
        <%= f.submit "View Schema", class: "btn-seeql btn-seeql-lg" %>
    <% end %>
</div>